theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
plugins:
  - safari
  - pagebreak
  - autoresize
#mode: exact, not necessary
convert_newlines_to_brs: false
remove_trailing_nbsp: true
theme_advanced_layout_manager: SimpleLayout
theme_advanced_buttons2: ''
theme_advanced_buttons3: ''
theme_advanced_resizing_use_cookie: false
theme_advanced_buttons1: "bold,italic,strikethrough,link,unlink,numlist,bullist,pagebreak,image,blockquote,code"
pagebreak_separator: "[[MORE]]"
convert_urls: false
process_html: true
inline_styles: false
gecko_spellcheck: true
content_css: ''
object_resizing: false
